[package]
name = "asset-log"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["trace", "cors"] }
sqlx = { version = "0.9", features = ["runtime-tokio", "postgres", "uuid", "chrono", "rust_decimal", "macros", "migrate"] }
rust_decimal = { version = "1", features = ["serde-with-str"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
jsonwebtoken = "9"
argon2 = "0.5"
reqwest = { version = "0.12", features = ["json", "rustls-tls" , "blocking"] }
async-trait = "0.1"
thiserror = "2"
anyhow = "1"
validator = { version = "0.19", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tokio-cron-scheduler = "0.13"
csv = "1"
clap = { version = "4.5", features = ["derive"] }
axum-extra = { version = "0.10", features = ["typed-header"] }
rand = "0.8"
dotenvy = "0.15.7"

[dev-dependencies]
wiremock = "0.6"
rstest = "0.23"
